module ActionDispatch::Routing
  class Mapper
    ##
    # # Method 1:
    # searchability_for :users # simple way
    #
    # # Method 2:
    # resources :users do # inside a resources route
    #   collection do
    #     searchable
    #   end
    # end
    #
    # TODO: consistent route helpers for search routes
    # When `searchability_for` is used the generated routes are postfixed as 
    # `ROUTE_query`, while route helpers generated by the `searchable` method
    # are postfixed `query_ROUTE`.
    # This is ugly as hell and I need to figure out a more consistent solution

    def searchability_for(resource, options={})
      get "#{resource}/query", to: "#{options[:controller] || resource}#query" #, as: "#{resource}_query"
    end

    def searchable
      if resource_scope?
        # TODO: raise not yet implemented
      else
        get("query", to: "#{parent_resource.controller}#query") if parent_resource # TODO: check for resource_scope? and throw error on failure
      end
    end

    private
    def route_format(resource)
      resource.to_s.underscore
    end
  end
end
